using System.CodeDom.Compiler;
using Microsoft.VisualBasic.CompilerServices;

namespace database.Database;

public class AutoGeneratedID
{
    private int _current = 1;
    public readonly string separator = "###";
    private static AutoGeneratedID? _instance;

    private AutoGeneratedID() {}

    public static AutoGeneratedID GetInstance()
    {
        if (_instance != null)
        {
            return _instance;
        }

        _instance = new AutoGeneratedID();

        return _instance;
    }

    public void LoadIds(string dsn)
    {
        foreach (string line in File.ReadLines(dsn))
        {
            string[] split = line.Split(separator);
            if (split.Length != 2)
            {
                return;
            }
            
            string id = split[0];
            if (int.TryParse(id, out int number))
            {
                _current = number + 1;
            }
            else
            {
                throw new IncompleteInitialization();
            }
        }
    }

    public string Generate()
    {
        int curr = _current++;
        return curr.ToString() + separator;
    }
}