namespace database.Database;

public class Reader: IReader
{
    private FileStream _stream;
    
    public Reader(FileStream stream)
    {
        _stream = stream;
    }
    
    public string Read(string id)
    {
        using (StreamReader reader = new StreamReader(_stream))
        {
            string? line;
            while ((line = reader.ReadLine()) != null)
            {
                string[] split = line.Split(AutoGeneratedID.GetInstance().separator);
                // id should be on the 0 index while value is in index 1
                string splitId = split[0];

                // we check if the id is correct and found and return the data associated
                // with it.
                if (splitId == id)
                {
                    return split[1];
                }
            }
        }

        return "";
    }
}