using System.Text;

namespace database.Database;

public class Writer: IWriter, IDisposable
{
    private FileStream _stream;
    
    public Writer(FileStream stream)
    {
        _stream = stream;
    }
    
    public int Write(string value)
    {
        string generatedId = AutoGeneratedID.GetInstance().Generate();
        string idValue = generatedId + value;

        byte[] info = new UTF8Encoding(false).GetBytes(idValue);
        
        _stream.Write(info, 0, info.Length);
        _stream.Flush();

        return info.Length;
    }

    public void Dispose()
    {
        _stream.Close();
    }
}